"""
Shared schema comparison helpers for migration tests.

Used by both the router and provider migration test suites.
"""


def _extract_checks(sql):
    """Extract CHECK(...) clauses from a CREATE TABLE statement, with balanced
    parens and normalised whitespace. Returns a sorted list."""
    if sql is None:
        return []
    upper = sql.upper()
    checks = []
    i = 0
    n = len(sql)
    while i < n:
        idx = upper.find("CHECK", i)
        if idx == -1:
            break
        # require CHECK to be a standalone keyword (bounded by non-word chars)
        prev = sql[idx - 1] if idx > 0 else " "
        if prev.isalnum() or prev == "_":
            i = idx + 5
            continue
        j = idx + 5
        while j < n and sql[j].isspace():
            j += 1
        if j >= n or sql[j] != "(":
            i = idx + 5
            continue
        depth = 0
        start = j
        while j < n:
            c = sql[j]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    j += 1
                    break
            j += 1
        checks.append(" ".join(sql[start:j].split()))
        i = j
    return sorted(checks)


def _table_constraints(db, tbl_name, tbl_sql):
    """Return FK list, full index list (incl. autogenerated), and CHECK
    clauses for a single table."""
    fks = []
    for row in db.execute(f"PRAGMA foreign_key_list({tbl_name})").fetchall():
        # (id, seq, table, from, to, on_update, on_delete, match)
        fks.append(
            {
                "table": row[2],
                "from": row[3],
                "to": row[4],
                "on_update": row[5],
                "on_delete": row[6],
                "match": row[7],
            }
        )
    # FK rows can come back in any order across platforms; sort for stable diff.
    fks.sort(key=lambda fk: (fk["table"], fk["from"], fk["to"]))

    indexes = {}
    for row in db.execute(f"PRAGMA index_list({tbl_name})").fetchall():
        # (seq, name, unique, origin, partial)
        idx_name = row[1]
        cols = [info[2] for info in db.execute(f"PRAGMA index_info({idx_name})").fetchall()]
        indexes[idx_name] = {
            "unique": row[2],
            "origin": row[3],  # 'c' = CREATE INDEX, 'u' = UNIQUE, 'pk' = PRIMARY KEY
            "partial": row[4],
            "columns": cols,
        }

    return {
        "foreign_keys": fks,
        "indexes": indexes,
        "checks": _extract_checks(tbl_sql),
    }


def _autoindex_signatures(constraints):
    """Collapse autogenerated index entries (names like ``sqlite_autoindex_*``)
    down to their shape — ``(origin, unique, partial, columns)`` — so that two
    schemas that differ only in SQLite's numbering for inline UNIQUE / PK
    indexes still compare equal."""
    sigs = []
    for name, info in constraints["indexes"].items():
        if name.startswith("sqlite_autoindex_"):
            sigs.append(
                (
                    info["origin"],
                    info["unique"],
                    info["partial"],
                    tuple(info["columns"]),
                )
            )
    return sorted(sigs)


def get_schema_snapshot(db):
    """Return a normalised dict describing every table, column, index, and
    constraint (FK, inline UNIQUE via autoindexes, CHECK).

    Shape:
        {
            "tables":            {tbl: {col: {type, notnull, default, pk}}},
            "indexes":           {idx_name: {table, sql}},             # named
            "table_constraints": {tbl: {foreign_keys, indexes, checks}},
        }

    The ``tables`` sub-dict keeps the legacy flat-column shape so older
    callers (e.g. ``"public_paths" in snap["tables"]["apps"]``) still work.
    """
    snapshot = {"tables": {}, "indexes": {}, "table_constraints": {}}

    tables = db.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ).fetchall()

    for tbl_name, tbl_sql in tables:
        cols = {}
        for row in db.execute(f"PRAGMA table_info({tbl_name})").fetchall():
            # row: (cid, name, type, notnull, dflt_value, pk)
            cols[row[1]] = {
                "type": row[2],
                "notnull": row[3],
                "default": row[4],
                "pk": row[5],
            }
        snapshot["tables"][tbl_name] = cols
        snapshot["table_constraints"][tbl_name] = _table_constraints(db, tbl_name, tbl_sql)

    indexes = db.execute(
        "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"
    ).fetchall()
    for name, tbl_name, sql in indexes:
        snapshot["indexes"][name] = {"table": tbl_name, "sql": sql}

    return snapshot


def normalise_default(val):
    """Strip outer single-quotes from default values for comparison."""
    if val is None:
        return None
    val = val.strip()
    if len(val) >= 2 and val[0] == "'" and val[-1] == "'":
        return val[1:-1]
    return val


def _normalise_index_sql(sql):
    """Normalise index DDL so semantically identical indexes compare equal.

    SQLite stores the original DDL text, so ``CREATE INDEX IF NOT EXISTS idx``
    and ``CREATE INDEX idx`` would differ textually despite being equivalent.
    """
    if sql is None:
        return None
    return sql.replace("IF NOT EXISTS ", "")


def assert_schemas_equal(fresh_snap, migrated_snap):
    """Compare two schema snapshots and produce a clear diff on failure."""
    fresh_tables = set(fresh_snap["tables"])
    migrated_tables = set(migrated_snap["tables"])
    assert fresh_tables == migrated_tables, (
        f"Table mismatch.\n"
        f"  Only in fresh: {fresh_tables - migrated_tables}\n"
        f"  Only in migrated: {migrated_tables - fresh_tables}"
    )

    for tbl in sorted(fresh_tables):
        fresh_cols = fresh_snap["tables"][tbl]
        migrated_cols = migrated_snap["tables"][tbl]

        fresh_names = set(fresh_cols)
        migrated_names = set(migrated_cols)
        assert fresh_names == migrated_names, (
            f"Column mismatch in table '{tbl}'.\n"
            f"  Only in fresh: {fresh_names - migrated_names}\n"
            f"  Only in migrated: {migrated_names - fresh_names}"
        )

        for col in sorted(fresh_names):
            fc = fresh_cols[col]
            mc = migrated_cols[col]
            assert fc["type"] == mc["type"], (
                f"Type mismatch: {tbl}.{col}: fresh={fc['type']!r}, migrated={mc['type']!r}"
            )
            assert fc["notnull"] == mc["notnull"], (
                f"NOT NULL mismatch: {tbl}.{col}: fresh={fc['notnull']}, migrated={mc['notnull']}"
            )
            assert fc["pk"] == mc["pk"], f"PK mismatch: {tbl}.{col}: fresh={fc['pk']}, migrated={mc['pk']}"
            fd = normalise_default(fc["default"])
            md = normalise_default(mc["default"])
            assert fd == md, f"Default mismatch: {tbl}.{col}: fresh={fd!r}, migrated={md!r}"

        # Compare per-table constraints (FKs, autoindex shapes, CHECKs). Named
        # indexes are compared below in the existing ``indexes`` block.
        fresh_cons = fresh_snap["table_constraints"][tbl]
        migrated_cons = migrated_snap["table_constraints"][tbl]

        assert fresh_cons["foreign_keys"] == migrated_cons["foreign_keys"], (
            f"Foreign key mismatch in table '{tbl}':\n"
            f"  fresh:    {fresh_cons['foreign_keys']}\n"
            f"  migrated: {migrated_cons['foreign_keys']}"
        )

        assert fresh_cons["checks"] == migrated_cons["checks"], (
            f"CHECK constraint mismatch in table '{tbl}':\n"
            f"  fresh:    {fresh_cons['checks']}\n"
            f"  migrated: {migrated_cons['checks']}"
        )

        # Autoindex entries (inline UNIQUE, PK) get different numeric suffixes
        # across DBs, so compare their shapes rather than their names.
        fresh_auto = _autoindex_signatures(fresh_cons)
        migrated_auto = _autoindex_signatures(migrated_cons)
        assert fresh_auto == migrated_auto, (
            f"Inline UNIQUE / PK index mismatch in table '{tbl}':\n"
            f"  fresh:    {fresh_auto}\n"
            f"  migrated: {migrated_auto}"
        )

    # Compare indexes — names first, then definitions
    fresh_idx = set(fresh_snap["indexes"])
    migrated_idx = set(migrated_snap["indexes"])
    assert fresh_idx == migrated_idx, (
        f"Index mismatch.\n  Only in fresh: {fresh_idx - migrated_idx}\n  Only in migrated: {migrated_idx - fresh_idx}"
    )

    for idx_name in sorted(fresh_idx):
        fi = fresh_snap["indexes"][idx_name]
        mi = migrated_snap["indexes"][idx_name]
        assert fi["table"] == mi["table"], (
            f"Index table mismatch for '{idx_name}': fresh={fi['table']!r}, migrated={mi['table']!r}"
        )
        f_sql = _normalise_index_sql(fi["sql"])
        m_sql = _normalise_index_sql(mi["sql"])
        assert f_sql == m_sql, (
            f"Index SQL mismatch for '{idx_name}':\n  fresh:    {fi['sql']}\n  migrated: {mi['sql']}"
        )
