"""Remove the obsolete iptables hairpin NAT rules and persistence script.

Same-hostname HTTPS access from pasta containers is now handled by a
container-facing CoreDNS view (resolving the zone wildcard to the gateway,
which the app containers use via ``--dns``) instead of OUTPUT DNAT rules that
rewrote ``public_ip:80/443`` to ``127.0.0.1``.  Those rules never worked for
pasta containers (the public IP is local to the container netns, and 127.0.0.1
there has no Caddy) and are now dead weight.

This migration drops them from hosts provisioned before the change.  It is
idempotent and safe: it only removes rules/files that the old code created, and
deleting a non-existent rule/file is a no-op.  The container DNS view itself is
generated by the router process at startup (see compute_space.core.dns), so no
host-level setup is needed here for the new behaviour.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from openhost_system_agent.migrations.base import SystemMigration

_OBSOLETE_PERSISTENCE_SCRIPTS = (
    "/etc/networkd-dispatcher/routable.d/50-openhost-hairpin-nat",
    "/etc/networkd-dispatcher/routable.d/50-openhost-firewall",
)


def _detect_public_ip() -> str | None:
    """Best-effort public IP, mirroring the old persistence script's logic."""
    try:
        out = subprocess.run(["hostname", "-I"], capture_output=True, text=True, check=False).stdout
        ip = out.split()[0] if out.split() else ""
    except OSError:
        ip = ""
    private_prefixes = ("10.", "192.168.")
    is_private = (
        ip.startswith(private_prefixes)
        or any(ip.startswith(f"172.{n}.") for n in range(16, 32))
    )
    if not ip or is_private:
        try:
            out = subprocess.run(
                ["curl", "-sf", "--max-time", "5", "https://ifconfig.me"],
                capture_output=True,
                text=True,
                check=False,
            ).stdout.strip()
            if out:
                ip = out
        except OSError:
            pass
    return ip or None


class Migration0003RemoveObsoleteHairpinNat(SystemMigration):
    version = 3

    def up(self) -> None:
        self._remove_dnat_rules()
        self._remove_persistence_scripts()

    def _remove_dnat_rules(self) -> None:
        public_ip = _detect_public_ip()
        if not public_ip:
            return
        for port in ("80", "443"):
            rule = [
                "-t", "nat",
                "-p", "tcp",
                "-d", public_ip,
                "--dport", port,
                "-j", "DNAT",
                "--to-destination", f"127.0.0.1:{port}",
            ]
            # Delete every copy of the rule (older code could append duplicates).
            while subprocess.run(["iptables", "-C", "OUTPUT", *rule], capture_output=True).returncode == 0:
                if subprocess.run(["iptables", "-D", "OUTPUT", *rule]).returncode != 0:
                    break

    def _remove_persistence_scripts(self) -> None:
        for path in _OBSOLETE_PERSISTENCE_SCRIPTS:
            Path(path).unlink(missing_ok=True)
