-- Generated by regenerate.py — do not edit by hand.
-- Scenario: scenario_refresh_tokens
-- After migration: 0002_dummy

BEGIN TRANSACTION;
CREATE TABLE api_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE app_databases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_name TEXT NOT NULL,
    db_name TEXT NOT NULL,
    db_path TEXT NOT NULL,
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE,
    UNIQUE(app_name, db_name)
);
CREATE TABLE app_port_mappings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_name TEXT NOT NULL,
    label TEXT NOT NULL,
    container_port INTEGER NOT NULL,
    host_port INTEGER NOT NULL,
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE,
    UNIQUE(app_name, label)
);
CREATE TABLE app_tokens (
    app_name TEXT PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE
);
CREATE TABLE apps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    manifest_name TEXT NOT NULL DEFAULT '',
    version TEXT NOT NULL,
    description TEXT,
    runtime_type TEXT NOT NULL DEFAULT 'serverfull',
    repo_path TEXT NOT NULL,
    repo_url TEXT,
    health_check TEXT,
    local_port INTEGER NOT NULL UNIQUE,
    container_port INTEGER,
    docker_container_id TEXT,
    status TEXT NOT NULL DEFAULT 'stopped' CHECK(status IN ('building', 'starting', 'running', 'stopped', 'error')),
    error_message TEXT,
    memory_mb INTEGER NOT NULL DEFAULT 128,
    cpu_millicores INTEGER NOT NULL DEFAULT 100,
    gpu INTEGER NOT NULL DEFAULT 0,
    public_paths TEXT NOT NULL DEFAULT '[]',
    manifest_raw TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE owner (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    password_needs_set INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE permissions (
    consumer_app TEXT NOT NULL,
    permission_key TEXT NOT NULL,
    PRIMARY KEY (consumer_app, permission_key),
    FOREIGN KEY (consumer_app) REFERENCES apps(name) ON DELETE CASCADE
);
CREATE TABLE refresh_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token_hash TEXT UNIQUE NOT NULL,
    expires_at TEXT NOT NULL,
    revoked INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE service_providers (
    service_name TEXT NOT NULL,
    app_name TEXT NOT NULL,
    PRIMARY KEY (service_name, app_name),
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE
);
CREATE INDEX idx_apps_status ON apps(status);
CREATE UNIQUE INDEX idx_port_mappings_host_port ON app_port_mappings(host_port);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);
CREATE TABLE "_yoyo_log" (
            "id" VARCHAR(36),
            "migration_hash" VARCHAR(64),
            "migration_id" VARCHAR(255),
            "operation" VARCHAR(10),
            "username" VARCHAR(255),
            "hostname" VARCHAR(255),
            "comment" VARCHAR(255),
            "created_at_utc" TIMESTAMP,
            PRIMARY KEY ("id")
        );
CREATE TABLE "_yoyo_migration" (
            "migration_hash" VARCHAR(64),
            "migration_id" VARCHAR(255),
            "applied_at_utc" TIMESTAMP,
            PRIMARY KEY ("migration_hash")
        );
CREATE TABLE "_yoyo_version" (
            "version" INT NOT NULL PRIMARY KEY,
            "installed_at_utc" TIMESTAMP
        );
CREATE TABLE "yoyo_lock" ("locked" INT DEFAULT 1, "ctime" TIMESTAMP,"pid" INT NOT NULL,PRIMARY KEY ("locked"));
INSERT INTO "owner" (id, username, password_hash, password_needs_set, created_at) VALUES (1, 'admin', NULL, 1, '2025-01-01T00:00:00');
INSERT INTO "refresh_tokens" (id, token_hash, expires_at, revoked) VALUES (1, '3981be392096cbf5a753cdda521da30a43ad920fe274e33d03b7f23419ae9cee', '2099-01-01T00:00:00', 0);
INSERT INTO "refresh_tokens" (id, token_hash, expires_at, revoked) VALUES (2, 'f0623f29acd0708e6319726f14b3f7e5e4ae9860c4f6c14ec3e1115abc8dbc3b', '2099-01-01T00:00:00', 1);
INSERT INTO "refresh_tokens" (id, token_hash, expires_at, revoked) VALUES (3, 'c26b7d992abc3171ca60f6816d5f3cd6bd12628514f894f3255a9fff4f4b96a3', '2000-01-01T00:00:00', 0);
INSERT INTO "refresh_tokens" (id, token_hash, expires_at, revoked) VALUES (4, '50ab7e52783c1fe8e9d7866f9debe9fbae73697cdfe8de8748e55f4d2b375058', '2000-01-01T00:00:00', 1);
INSERT INTO "_yoyo_migration" (migration_hash, migration_id, applied_at_utc) VALUES ('25d06ca362a6cbcfa89d5e102a1660c576d0da583e97bd39a387aa08633511b4', '0002_dummy', '2025-01-01 00:00:00');
INSERT INTO "_yoyo_migration" (migration_hash, migration_id, applied_at_utc) VALUES ('3ef54af11f5dd6ae30463e2a77ee651fb81022a58928acccdd9ff64181d79745', '0001_initial', '2025-01-01 00:00:00');
INSERT INTO "_yoyo_version" (version, installed_at_utc) VALUES (2, '2025-01-01 00:00:00');
COMMIT;
