set-option -g default-shell "$SHELL"
set-option -g history-limit 100000
set-option -g status-keys vi

# make new terminals go at the bottom of the list.
# by default they will fill in index values of closed terminals
bind c new-window -a
