"""Frozen legacy migration system.

DO NOT add new migration logic here. Since the SQLAlchemy + Alembic migration
landed (see db/alembic/), all schema evolution is expressed as Alembic
revisions. This module exists only to bring legacy databases (created before
the Alembic cutover) up to the baseline schema on first boot; after that
first run the database is stamped with the baseline Alembic revision and
this module never executes again.
"""

import hashlib
import re
import sqlite3

# Inlined copy of the baseline (legacy schema.sql) DDL. Frozen together with
# the rest of this module so ``grep "CREATE TABLE"`` only hits this file and
# autogenerated Alembic revisions. Kept character-for-character equivalent to
# the Alembic baseline migration to guarantee schema parity.
_BASELINE_SCHEMA: str = """
CREATE TABLE IF NOT EXISTS apps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    manifest_name TEXT NOT NULL DEFAULT '',
    version TEXT NOT NULL,
    description TEXT,
    runtime_type TEXT NOT NULL DEFAULT 'serverfull',
    repo_path TEXT NOT NULL,
    repo_url TEXT,
    health_check TEXT,
    local_port INTEGER NOT NULL UNIQUE,
    container_port INTEGER,
    docker_container_id TEXT,
    status TEXT NOT NULL DEFAULT 'stopped' CHECK(status IN ('building', 'starting', 'running', 'stopped', 'error')),
    error_message TEXT,
    memory_mb INTEGER NOT NULL DEFAULT 128,
    cpu_millicores INTEGER NOT NULL DEFAULT 100,
    gpu INTEGER NOT NULL DEFAULT 0,
    public_paths TEXT NOT NULL DEFAULT '[]',
    manifest_raw TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS app_databases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_name TEXT NOT NULL,
    db_name TEXT NOT NULL,
    db_path TEXT NOT NULL,
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE,
    UNIQUE(app_name, db_name)
);

CREATE TABLE IF NOT EXISTS app_port_mappings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_name TEXT NOT NULL,
    label TEXT NOT NULL,
    container_port INTEGER NOT NULL,
    host_port INTEGER NOT NULL,
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE,
    UNIQUE(app_name, label)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_port_mappings_host_port ON app_port_mappings(host_port);
CREATE INDEX IF NOT EXISTS idx_apps_status ON apps(status);

CREATE TABLE IF NOT EXISTS owner (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    password_needs_set INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token_hash TEXT UNIQUE NOT NULL,
    expires_at TEXT NOT NULL,
    revoked INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);

CREATE TABLE IF NOT EXISTS api_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS app_tokens (
    app_name TEXT PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS service_providers (
    service_name TEXT NOT NULL,
    app_name TEXT NOT NULL,
    PRIMARY KEY (service_name, app_name),
    FOREIGN KEY (app_name) REFERENCES apps(name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS permissions (
    consumer_app TEXT NOT NULL,
    permission_key TEXT NOT NULL,
    PRIMARY KEY (consumer_app, permission_key),
    FOREIGN KEY (consumer_app) REFERENCES apps(name) ON DELETE CASCADE
);
"""


def _recreate_table(db: sqlite3.Connection, table_name: str, keep_cols: list[str]) -> None:
    """Recreate a table using the baseline schema, preserving data.

    This handles cases where SQLite cannot ALTER TABLE (e.g. dropping columns
    with UNIQUE constraints, or changing NOT NULL on existing columns).
    ``keep_cols`` is the list of column names to copy from the old table;
    only columns that also exist in the new schema are actually copied.
    """
    pattern = rf"CREATE TABLE IF NOT EXISTS {re.escape(table_name)} \([^;]+\);"
    m = re.search(pattern, _BASELINE_SCHEMA, re.DOTALL)
    if m is None:
        raise RuntimeError(f"Could not find CREATE TABLE {table_name} statement in baseline schema")

    tmp_name = f"{table_name}_new"
    create_sql = m.group().replace(f"CREATE TABLE IF NOT EXISTS {table_name}", f"CREATE TABLE {tmp_name}")

    # Drop any leftover temp table from a prior failed run so the CREATE
    # below doesn't fail if init_db() crashed mid-recreation previously.
    db.execute(f"DROP TABLE IF EXISTS {tmp_name}")

    db.execute(create_sql)
    new_col_info = {row[1]: row for row in db.execute(f"PRAGMA table_info({tmp_name})").fetchall()}
    common_cols = [c for c in keep_cols if c in new_col_info]
    cols_csv = ", ".join(common_cols)

    # Build SELECT expressions: wrap NOT NULL columns with COALESCE so that
    # NULL values in old rows get replaced by the column's default rather
    # than violating the constraint.  (SQLite only applies DEFAULT on INSERT
    # when a column is omitted, not when it's explicitly NULL.)
    select_exprs = []
    for c in common_cols:
        info = new_col_info[c]
        notnull, dflt = info[3], info[4]
        if notnull and dflt is not None:
            select_exprs.append(f"COALESCE({c}, {dflt})")
        else:
            select_exprs.append(c)
    select_csv = ", ".join(select_exprs)

    db.execute(f"INSERT INTO {tmp_name} ({cols_csv}) SELECT {select_csv} FROM {table_name}")
    db.execute(f"DROP TABLE {table_name}")
    db.execute(f"ALTER TABLE {tmp_name} RENAME TO {table_name}")
    db.commit()


def _recover_temp_tables(db: sqlite3.Connection) -> None:
    """Recover from a prior crash that left temp tables from _recreate_table."""
    for table_name in ("apps", "owner", "refresh_tokens", "app_tokens"):
        tmp_name = f"{table_name}_new"
        orig_exists = db.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
            (table_name,),
        ).fetchone()
        if not orig_exists:
            tmp_exists = db.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
                (tmp_name,),
            ).fetchone()
            if tmp_exists:
                db.execute(f"ALTER TABLE {tmp_name} RENAME TO {table_name}")
                db.commit()


def migrate(db: sqlite3.Connection) -> None:
    """Bring a legacy pre-Alembic database up to the baseline schema.

    Only called once per database — the first boot after the Alembic cutover.
    After this runs, the DB is stamped with the baseline Alembic revision and
    future schema changes go through ``alembic upgrade``. This function is
    frozen; do not add new logic.
    """
    _recover_temp_tables(db)
    cursor = db.execute("PRAGMA table_info(apps)")
    columns = {row[1] for row in cursor.fetchall()}
    if not columns:
        # Fresh DB — no legacy tables to migrate. Baseline will be applied by
        # Alembic directly.
        return

    if "public_paths" not in columns:
        db.execute("ALTER TABLE apps ADD COLUMN public_paths TEXT NOT NULL DEFAULT '[]'")
        db.commit()

    if "manifest_name" not in columns:
        db.execute("ALTER TABLE apps ADD COLUMN manifest_name TEXT NOT NULL DEFAULT ''")
        db.execute("UPDATE apps SET manifest_name = name")
        db.commit()

    cursor = db.execute("PRAGMA table_info(apps)")
    columns = {row[1] for row in cursor.fetchall()}

    drop_cols = {"base_path", "subdomain"} & columns
    if drop_cols:
        db.execute("PRAGMA foreign_keys=OFF")
        try:
            keep_cols = [c for c in columns if c not in drop_cols]
            _recreate_table(db, "apps", keep_cols)
        finally:
            db.execute("PRAGMA foreign_keys=ON")

    cursor = db.execute("PRAGMA table_info(apps)")
    columns = {row[1] for row in cursor.fetchall()}

    if "repo_url" not in columns:
        db.execute("ALTER TABLE apps ADD COLUMN repo_url TEXT")
        db.commit()

    cursor = db.execute("PRAGMA table_info(apps)")
    columns = {row[1] for row in cursor.fetchall()}

    if "spin_pid" in columns:
        db.execute("PRAGMA foreign_keys=OFF")
        try:
            keep_cols = [c for c in columns if c != "spin_pid"]
            _recreate_table(db, "apps", keep_cols)
        finally:
            db.execute("PRAGMA foreign_keys=ON")

    cursor = db.execute("PRAGMA table_info(owner)")
    owner_rows = cursor.fetchall()
    owner_columns = {row[1] for row in owner_rows}

    needs_recreate = False
    if owner_columns:
        for row in owner_rows:
            if row[1] == "password_hash" and row[3] == 1:
                needs_recreate = True
                break
        if "password_needs_set" not in owner_columns:
            needs_recreate = True

    if needs_recreate and owner_columns:
        db.execute("PRAGMA foreign_keys=OFF")
        try:
            _recreate_table(db, "owner", list(owner_columns))
        finally:
            db.execute("PRAGMA foreign_keys=ON")

    db.execute("DROP TABLE IF EXISTS app_object_stores")
    db.commit()

    # Migrate refresh_tokens: hash plaintext values and drop the old column.
    rt_cols = {row[1] for row in db.execute("PRAGMA table_info(refresh_tokens)").fetchall()}
    if "token" in rt_cols and "token_hash" not in rt_cols:
        db.execute("ALTER TABLE refresh_tokens ADD COLUMN token_hash TEXT")
        rows = db.execute("SELECT id, token FROM refresh_tokens").fetchall()
        for row in rows:
            hashed = hashlib.sha256(row[1].encode()).hexdigest()
            db.execute("UPDATE refresh_tokens SET token_hash = ? WHERE id = ?", (hashed, row[0]))
        db.commit()
    rt_cols = {row[1] for row in db.execute("PRAGMA table_info(refresh_tokens)").fetchall()}
    if "token" in rt_cols:
        db.execute("PRAGMA foreign_keys=OFF")
        try:
            _recreate_table(db, "refresh_tokens", [c for c in rt_cols if c != "token"])
        finally:
            db.execute("PRAGMA foreign_keys=ON")

    # Migrate app_tokens: hash plaintext values and drop the old column.
    at_cols = {row[1] for row in db.execute("PRAGMA table_info(app_tokens)").fetchall()}
    if "token" in at_cols and "token_hash" not in at_cols:
        db.execute("ALTER TABLE app_tokens ADD COLUMN token_hash TEXT")
        rows = db.execute("SELECT app_name, token FROM app_tokens").fetchall()
        for row in rows:
            hashed = hashlib.sha256(row[1].encode()).hexdigest()
            db.execute("UPDATE app_tokens SET token_hash = ? WHERE app_name = ?", (hashed, row[0]))
        db.commit()
    at_cols = {row[1] for row in db.execute("PRAGMA table_info(app_tokens)").fetchall()}
    if "token" in at_cols:
        db.execute("PRAGMA foreign_keys=OFF")
        try:
            _recreate_table(db, "app_tokens", [c for c in at_cols if c != "token"])
        finally:
            db.execute("PRAGMA foreign_keys=ON")

    # Finalise: ensure every baseline table and index exists. This mirrors
    # the old ``init_db`` that always executed schema.sql after migrate(), and
    # is the last point at which this frozen module touches DDL.
    db.executescript(_BASELINE_SCHEMA)
    db.commit()
