#!/usr/bin/env python3
"""Regenerate every ``at_NNNN.sql`` snapshot for every scenario.

Run: ``uv run python compute_space/tests/fixtures/migrations/regenerate.py``

For each scenario directory (``scenario_*``) this walks the yoyo
migrations folder in order; after applying each migration it calls the
scenario's ``seed_at(conn, migration_id)`` hook and dumps the resulting
database to ``at_<prefix>.sql``.  Re-running is idempotent as long as the
migrations and seeds are unchanged.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
import tempfile
from pathlib import Path

# Make the shared harness importable as a top-level module when invoked as
# a plain script.  ``compute_space.tests`` is not a real subpackage of the
# installed ``compute_space`` wheel — tests live on disk alongside it — so
# we put the tests directory on ``sys.path`` and import directly.
_TESTS_DIR = Path(__file__).resolve().parents[2]
_REPO_ROOT = Path(__file__).resolve().parents[4]
for _p in (_REPO_ROOT, _TESTS_DIR):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

from _snapshot_harness import discover_scenario_dirs  # noqa: E402
from _snapshot_harness import dump_application_db  # noqa: E402
from _snapshot_harness import fixture_path  # noqa: E402
from _snapshot_harness import list_migration_ids  # noqa: E402
from _snapshot_harness import load_scenario_builder  # noqa: E402
from _snapshot_harness import scenario_seed_fn  # noqa: E402
from _snapshot_harness import walk_migrations  # noqa: E402


def regenerate_scenario(scenario_dir: Path) -> list[Path]:
    """Produce every ``at_*.sql`` for ``scenario_dir``.  Returns written paths."""
    builder = load_scenario_builder(scenario_dir)
    seed_fn = scenario_seed_fn(builder)
    migration_ids = list_migration_ids()

    written: list[Path] = []
    with tempfile.TemporaryDirectory() as tmp:
        db_path = os.path.join(tmp, "gen.db")
        # Empty file: no tables yet, ready for the first migration.
        sqlite3.connect(db_path).close()

        previous: str | None = None
        for mid in migration_ids:
            walk_migrations(db_path, from_exclusive=previous, to_inclusive=mid, seed_fn=seed_fn)
            previous = mid

            conn = sqlite3.connect(db_path)
            try:
                dump = dump_application_db(
                    conn,
                    header_lines=[
                        "Generated by regenerate.py — do not edit by hand.",
                        f"Scenario: {scenario_dir.name}",
                        f"After migration: {mid}",
                    ],
                )
            finally:
                conn.close()

            out = fixture_path(scenario_dir, mid)
            out.write_text(dump)
            written.append(out)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any snapshot would change rather than writing",
    )
    args = parser.parse_args()

    scenario_dirs = discover_scenario_dirs()
    if not scenario_dirs:
        print("No scenarios found.", file=sys.stderr)
        return 1

    drift = False
    for scenario_dir in scenario_dirs:
        existing: dict[Path, str] = {}
        for p in scenario_dir.glob("at_*.sql"):
            existing[p] = p.read_text()

        written = regenerate_scenario(scenario_dir)
        print(f"{scenario_dir.name}: {len(written)} snapshot(s)")

        if args.check:
            for p in written:
                if existing.get(p) != p.read_text():
                    drift = True
                    print(f"  drift: {p.relative_to(scenario_dir.parent)}", file=sys.stderr)

    if args.check and drift:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
